# Generated by Django 5.0.6 on 2024-06-06 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Doctor', '0007_alter_image_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='Fullname',
            new_name='Patient_Name',
        ),
    ]
