# Generated by Django 5.0.6 on 2024-06-08 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Doctor', '0008_rename_fullname_image_patient_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='Patient_Name',
            new_name='Patient_name',
        ),
    ]
